### ISSUE TITLE
请问板载wifi速率和稳定性怎么样？

### ISSUE THREAD

**Issue by wooleo** [altjz/NUC8I5BEH-EFI#2]
如果还可以的话，我也准备换板载WiFi，NVME硬盘

**Comment by altjz** [comment]
目前没什么问题，我测过了，和我之前的 bcm94360cs2 差别不大，除了不能用 AirDrop，Handoff 之外（Android 手机，我也用不上）。

另外解决了之前休眠问题，之前休眠老是会自动唤醒（网卡的USB 供电问题）。

**Comment by wooleo** [comment]
试了下，比在windows下的速度差了很多，大概50mbps，windows下可以600mbps，一般够用了。

应该是只能跑到20MHZ的原因了：https://github.com/OpenIntelWireless/itlwm/issues/253

Alex <notifications@github.com> 于2020年8月22日周六 下午11:55写道：
