### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Yohahaha** [altjz/NUC8I5BEH-EFI#4]
非常感谢提供的这个repo，对我来说是完美的。

内存：镁光16G*2
SSD：sn550 1T
显示器：优派vx27804K
蓝牙正常
唤醒正常
HDMI和雷电口均可以输出4K40hz信号

**Comment by Yohahaha** [comment]
有一个小问题，magic keyboard无法调节屏幕亮度

**Comment by altjz** [comment]
> 有一个小问题，magic keyboard无法调节屏幕亮度

一般来说 HDMI 是无法通过系统调节亮度的，就算你在 Mac 下用 HDMI 也是无法调节亮度的，不过通过 DP 可以支持，但我不知道你的显示器支不支持，你可以试试，这个跟黑苹果没关系，是 Mac 系统的问题

你可以参考一下下面的：
[发现了调整外置显示器原生亮度的 BrightnessMenulet](https://www.v2ex.com/t/337027#reply0)
[BrightnessMenulet](https://github.com/superduper/BrightnessMenulet)

**Comment by Yohahaha** [comment]
用的typec-dp，找到解决方法了。
下载[MonitorControl](https://github.com/MonitorControl/MonitorControl)

**Comment by altjz** [comment]
> 用的typec-dp，找到解决方法了。
> 下载[MonitorControl](https://github.com/MonitorControl/MonitorControl)

DP 是可以用的
